name: hacs-validation

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: arc-runner-tendrilgrow-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
