name: hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: arc-runner-tendrilgrow-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
